# Generated by Django 4.2.7 on 2023-11-20 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessInfo',
            fields=[
                ('business_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, null=True)),
                ('employee_size', models.IntegerField(null=True)),
                ('owner_info', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Business Information',
                'db_table': 'business_info',
            },
        ),
        migrations.CreateModel(
            name='InvestmentStage',
            fields=[
                ('stage_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('stage', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Investment Stage',
                'db_table': 'investment_stage',
            },
        ),
        migrations.CreateModel(
            name='InvestorType',
            fields=[
                ('investor_type_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('investor_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Investor Type',
                'db_table': 'investor_type',
            },
        ),
        migrations.CreateModel(
            name='BusinessInvestor',
            fields=[
                ('business_investor_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_investor', to='organization.businessinfo')),
                ('business_investor_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_investor_type', to='organization.investortype')),
            ],
            options={
                'verbose_name_plural': 'Business Investor Type',
                'db_table': 'business_investor',
            },
        ),
        migrations.CreateModel(
            name='BusinessInvestmentStage',
            fields=[
                ('business_stage_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_investment', to='organization.businessinfo')),
                ('business_investment_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='business_investment_stage', to='organization.investmentstage')),
            ],
            options={
                'verbose_name_plural': 'Business Investment Stage',
                'db_table': 'business_investment_stage',
            },
        ),
        migrations.CreateModel(
            name='BusinessAddressInfo',
            fields=[
                ('address_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('country', models.CharField(max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_address', to='organization.businessinfo')),
            ],
            options={
                'verbose_name_plural': 'Business Address Information',
                'db_table': 'business_address_info',
            },
        ),
    ]
